#!/bin/bash

# vim :set ft=sh

# Return the name of the current branch
function current_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'; 
}

CURRENT_BRANCH=`current_branch`

# What branch are we tracking?
TRACKING=$(git config branch.${CURRENT_BRANCH}.merge | ruby -ne 'print $_.gsub(/refs\/heads\//, "").strip')

# What's the name of the remote?
REMOTE=$(git config branch.${CURRENT_BRANCH}.remote)

# Log options
OPTS="--pretty=oneline --abbrev-commit --decorate"

# URL of the remote we are tracking
REMOTE_URL=$(git remote -v | ruby -e "puts STDIN.each_line.grep(/^${REMOTE}/).first.split[1]")

# Fetch the changes from the remote.
echo "Fetching changes from '"${REMOTE}"' (${REMOTE_URL})"
git fetch

# E.g. for 'master':
#  git log master..origin/master
echo "Changes in the remote branch:"
env PAGER="" git log $OPTS ${CURRENT_BRANCH}..${REMOTE}/${TRACKING}

